;;***********************************************************************
;;***********************************************************************
;;
;; PGA_A.inc
;;
;; Assembler declarations for the PGA_A user module interface
;;
;; Rev B, 2002 Mar 30
;; 
;; Copyright: Cypress MicroSystems 2001-2002. All rights reserved
;;
;;***********************************************************************
;;***********************************************************************


SingleEnded_OFF:         equ 0
SingleEnded_LOWPOWER:    equ 1
SingleEnded_MEDPOWER:    equ 2
SingleEnded_HIGHPOWER:   equ 3

SingleEnded_G16_0:       equ 08h
SingleEnded_G8_00:       equ 18h
SingleEnded_G5_33:       equ 28h
SingleEnded_G4_00:       equ 38h
SingleEnded_G3_20:       equ 48h
SingleEnded_G2_67:       equ 58h
SingleEnded_G2_27:       equ 68h
SingleEnded_G2_00:       equ 78h
SingleEnded_G1_78:       equ 88h
SingleEnded_G1_60:       equ 98h
SingleEnded_G1_46:       equ A8h
SingleEnded_G1_33:       equ B8h
SingleEnded_G1_23:       equ C8h
SingleEnded_G1_14:       equ D8h
SingleEnded_G1_06:       equ E8h
SingleEnded_G1_00:       equ F8h
SingleEnded_G0_93:       equ E0h
SingleEnded_G0_87:       equ D0h
SingleEnded_G0_81:       equ C0h
SingleEnded_G0_75:       equ B0h
SingleEnded_G0_68:       equ A0h
SingleEnded_G0_62:       equ 90h
SingleEnded_G0_56:       equ 80h
SingleEnded_G0_50:       equ 70h
SingleEnded_G0_43:       equ 60h
SingleEnded_G0_37:       equ 50h
SingleEnded_G0_31:       equ 40h
SingleEnded_G0_25:       equ 30h
SingleEnded_G0_18:       equ 20h
SingleEnded_G0_12:       equ 10h
SingleEnded_G0_06:       equ 00h

SingleEnded_GAIN_CR0:   equ 79h
SingleEnded_GAIN_CR1:   equ 7ah
SingleEnded_GAIN_CR2:   equ 7bh

