;;***********************************************************************
;;***********************************************************************
;;
;; INSAMP.inc
;;
;; Assembler declarations for the INSAMP user module interface
;;
;; Rev A, 2002 Mar 30
;; 
;; Copyright: Cypress MicroSystems 2001-2002. All rights reserved
;;
;;***********************************************************************
;;***********************************************************************

DoubleEnded_OFF:        equ 0
DoubleEnded_LOWPOWER:   equ 1
DoubleEnded_MEDPOWER:   equ 2
DoubleEnded_HIGHPOWER:  equ 3

DoubleEnded_G16_0:       equ 00h
DoubleEnded_G8_00:       equ 10h
DoubleEnded_G5_33:       equ 20h
DoubleEnded_G4_00:       equ 30h
DoubleEnded_G3_20:       equ 40h
DoubleEnded_G2_67:       equ 50h
DoubleEnded_G2_27:       equ 60h
DoubleEnded_G2_00:       equ 70h



DoubleEnded_INV_CR0:    equ 71h
DoubleEnded_INV_CR1:    equ 72h
DoubleEnded_INV_CR2:    equ 73h

DoubleEnded_NON_INV_CR0:    equ 75h
DoubleEnded_NON_INV_CR1:    equ 76h
DoubleEnded_NON_INV_CR2:    equ 77h

